# .github/dependabot.yml
# Dependabot configuration to keep project dependencies updated daily.

version: 2
updates:

  # Daily checks for Gradle Dependencies (Kotlin, AndroidX, etc.)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily" # Checks for new versions every day
    open-pull-requests-limit: 10
    reviewers:
      - "AuraFrameFxDev" # OPTIONAL: Automatically assign yourself to review the PRs

  # Daily checks for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" # Checks for new versions every day
    open-pull-requests-limit: 5
